# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-15 17:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20160314_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2016, 3, 15, 17, 54, 21, 972236, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
